### ISSUE TITLE
Review Public API

### ISSUE THREAD

**Issue by marcellogalhardo** [deliveryhero/whetstone#1]
Our current API is working fine for our needs, but we may be able to improve it aiming to reduce cognitive load of developers using the library for the first time. For example, instead of multiple annotations we could come up with a couple of annotations and make the compiler smarter enough to understand what type is annotating.

The following proposal recommends:
```kotlin
// Members Injection.

@ContributesAndroidInjection
class MyApplication : Application() {
    fun onCreate() {
        Whetstone.inject(application = this)
    }
}

@ContributesAndroidInjection
class MyActivity : Activity() {
    fun onCreate() {
        Whetstone.inject(activity = this)
    }
}

@ContributesAndroidInjection
class MyService : Service() {
    fun onCreate() {
        Whetstone.inject(service = this)
    }
}

// Constructor Injection.

@ContributesAndroidBinding
class MyFragment @Inject constructor() : Fragment()

@ContributesAndroidBinding
class MyViewModel @Inject constructor() : ViewModel()

@ContributesAndroidBinding
class MyWorkManager @Inject constructor() : WorkManager()
```

For cases where "injection" is not required:
```kotlin
Whetstone.install(application = this)
Whetstone.install(activity = this)
```

As you can see, we can pretty much infer the target type and reduce all features to a couple of annotations: `ContributesAndroidInjection` for members injection and `ContributesAndroidBinding` for constructor injection (by using assisted injection).

We could also validate by type on the compiler level and by including a custom lint rule.

**Comment by kingsleyadio** [comment]
Closing as won't do. An alternative solution is now implemented in #60
